name: Unirest CI

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: windows-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
      - name: Checkout do código
        uses: actions/checkout@v2

      - name: Configurar Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Instalar dependencias
        run: npm install

      - name: Setar variaveis de ambiente
        run: |
          echo "BASE_URL=${{ secrets.BASE_URL }}" >> .env
          echo "USERNAME=${{ secrets.USERNAME }}" >> .env
          echo "PASSWORD=${{ secrets.PASSWORD }}" >> .env

      - name: Executar testes
        run: npm run test
